trigger:
- main

pool:
  name: 'Devpool'

steps:
# Ensure JAVA_HOME is correctly set
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-21"
    echo "##vso[task.setvariable variable=PATH]%JAVA_HOME%\bin;%PATH%"
  displayName: 'Set JAVA_HOME'

# Ensure Maven is available and in PATH
- script: |
    set PATH=C:\Users\apache-maven-3.9.9\bin;%PATH%
    echo "Maven path: C:\Users\apache-maven-3.9.9\bin"
  displayName: 'Set MAVEN_HOME'

# Verify Java & Maven installation
- script: |
    echo "Checking Java version..."
    java -version
    echo "Checking Maven version..."
    mvn -version
  displayName: 'Verify Java & Maven'

# Build with Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'DevOPS_Lab/happytails/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'  # Use installed Java 21 instead of 22
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -DskipTests'
  displayName: 'Build with Maven'
